// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ndreyserg/ushort/internal/app/handlers (interfaces: Queue)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// AddTask mocks base method.
func (m *MockQueue) AddTask(arg0 []string, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTask", arg0, arg1)
}

// AddTask indicates an expected call of AddTask.
func (mr *MockQueueMockRecorder) AddTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockQueue)(nil).AddTask), arg0, arg1)
}
